# This config is re-read each time a graph is being plotted

[beginner]
create_autostart_entry=false  # On Linux, create standard XDG autostart entry. Does nothing on other OS-es yet.
show_directories=true  # opens config directory and the resulting image

[main]
plot_days=5.0
sleep_minutes=1.0  # how long to wait for next iteration

[graph]
line_format="%category% (%hours%h)"  # Set to "" to hide completely.
show_day_labels=true
size="1920,300"
height_scale=2.0
smoothing=1.0


[category.work]
color="black"  # Example: "black", "#FF00CC", "#7FFF00CC"

[category.personal]
color="orange"

[category.fun]
color="red"
# Example command. Lock screen if it's too late (22:00) or too early (10:00).
# command=["sh", "-c", "(test $(date '+%k') -ge 22 || test $(date '+%k') -le 10) && xscreensaver-command -lock || true"]

[category.education]
color="green"

[category.skip]
hide=true
