# This config is re-read each time a graph is being plotted

[main]
plot_days=5.0
sleep_minutes=3.0  # how long to wait for next iteration (ideally 1-5 min)

[graph]
extension="svg"  # valid values: "svg", "pngcairo", "png"
line_format="%category% (%hours%h)"  # Set to "" to hide completely.
show_day_labels=true
size="1200 400"  # example: "1200 400" or "" (default, automatic svg resize)
height_scale=10.0  # default 1.0  Change this if you change size.
smoothing=1.0


[category.work]
color="black"  # names or codes "#FF00CC" are accepted

[category.personal]
color="orange"

[category.fun]
color="red"
# Example command. Lock screen if it's too late (22:00) or too early (10:00).
# command=["sh", "-c", "(test $(date '+%k') -ge 22 || test $(date '+%k') -le 10) && xscreensaver-command -lock || true"]
# TODO

[category.education]
color="green"

[category.skip]
hide=true
